/* eslint-disable @typescript-eslint/no-empty-object-type --
   auto-generated; empty Constructor interfaces are intentional for
   classes that have no class_function registrations. */
// ⚠️ AUTO-GENERATED by scripts/gen-module-types.py.
// Do not edit by hand. Re-run after changing src/cpp/bindings/*.cpp.
//
// Mirrors every Embind class_<X>('Name') registration and every
// .function('m', &X::method) call into a TypeScript interface so the
// TS wrapper (ts/*.ts) can call into WASM with type safety.

// Emscripten runtime symbols that aren't Embind-registered but are
// always present on the loaded module. EXPORTED_RUNTIME_METHODS in
// cmake/Emscripten.cmake controls which of these are exposed.
export interface EmscriptenRuntime {
  HEAPU8: Uint8Array;
  HEAPU32: Uint32Array;
  HEAP8: Int8Array;
  _malloc(bytes: number): number;
  _free(ptr: number): void;
  UTF8ToString(ptr: number): string;
  stringToUTF8(str: string, ptr: number, maxBytes: number): number;
  lengthBytesUTF8(str: string): number;
  ccall(name: string, ...args: unknown[]): unknown;
  cwrap(name: string, ...args: unknown[]): (...args: unknown[]) => unknown;
  addFunction(fn: (...args: unknown[]) => unknown, sig?: string): number;
  removeFunction(ptr: number): void;
  getExceptionMessage(ptr: number): string;
}

// Free-function declarations on the loaded module.
export interface RnpModule extends EmscriptenRuntime {
  rnpBootstrapFeatures(): string;
  rnpDecrypt(ffi: RnpFfiHandle, _in: RnpInputHandle, _out: RnpOutputHandle): void;
  rnpDumpPacketsToJson(_in: RnpInputHandle, flags: number): string;
  rnpDumpPacketsToOutput(_in: RnpInputHandle, _out: RnpOutputHandle, flags: number): void;
  rnpOpEncryptCreate(ffi: RnpFfiHandle, _in: RnpInputHandle, _out: RnpOutputHandle): RnpEncryptOpHandle;
  rnpVersionString(): string;
  rnpVersionStringFull(): string;
  rnpVersion(): number;
  rnpVersionCommitTimestamp(): number;
  rnpSupportsFeature(type: string, name: string): boolean;
  rnpSupportedFeatures(type: string): string;
  rnpCalculateIterations(hash: string, msec: number): number;
  rnpGenerateKeyCreate(ffi: RnpFfiHandle, alg: string): RnpGenerateOpHandle;
  rnpGenerateSubkeyCreate(ffi: RnpFfiHandle, primary: RnpKeyHandle, alg: string): RnpGenerateOpHandle;
  rnpGenerateKeyJson(ffi: RnpFfiHandle, json: string): string;
  rnpEnarmor(_in: RnpInputHandle, _out: RnpOutputHandle, type: string): void;
  rnpDearmor(_in: RnpInputHandle, _out: RnpOutputHandle): void;
  rnpGuessContents(_in: RnpInputHandle): string;
  rnpIdentifierIteratorCreate(ffi: RnpFfiHandle, item_type: string): RnpIdentifierIteratorHandle;
  rnpLoadKeys(ffi: RnpFfiHandle, format: string, input: RnpInputHandle, flags: number): void;
  rnpUnloadKeys(ffi: RnpFfiHandle, flags: number): void;
  rnpImportKeys(ffi: RnpFfiHandle, input: RnpInputHandle, flags: number): string;
  rnpImportSignatures(ffi: RnpFfiHandle, input: RnpInputHandle, flags: number): string;
  rnpSaveKeys(ffi: RnpFfiHandle, format: string, output: RnpOutputHandle, flags: number): void;
  rnpPublicKeyCount(ffi: RnpFfiHandle): number;
  rnpSecretKeyCount(ffi: RnpFfiHandle): number;
  rnpLocateKey(ffi: RnpFfiHandle, id_type: string, id: string): RnpKeyHandle;
  rnpOpSignCreate(ffi: RnpFfiHandle, _in: RnpInputHandle, _out: RnpOutputHandle): RnpSignOpHandle;
  rnpOpSignCleartextCreate(ffi: RnpFfiHandle, _in: RnpInputHandle, _out: RnpOutputHandle): RnpSignOpHandle;
  rnpOpSignDetachedCreate(ffi: RnpFfiHandle, _in: RnpInputHandle, _out: RnpOutputHandle): RnpSignOpHandle;
  rnpSignExecute(op: RnpSignOpHandle): void;
  rnpOpVerifyCreate(ffi: RnpFfiHandle, input: RnpInputHandle, output: RnpOutputHandle): RnpVerifyOpHandle;
  rnpOpVerifyDetachedCreate(ffi: RnpFfiHandle, input: RnpInputHandle, signature: RnpInputHandle): RnpVerifyOpHandle;
  RnpEncryptOpHandle: RnpEncryptOpHandleConstructor;
  RnpFfiHandle: RnpFfiHandleConstructor;
  RnpGenerateOpHandle: RnpGenerateOpHandleConstructor;
  RnpIdentifierIteratorHandle: RnpIdentifierIteratorHandleConstructor;
  RnpInputHandle: RnpInputHandleConstructor;
  RnpKeyHandle: RnpKeyHandleConstructor;
  RnpOutputHandle: RnpOutputHandleConstructor;
  RnpSignOpHandle: RnpSignOpHandleConstructor;
  RnpSignatureHandle: RnpSignatureHandleConstructor;
  RnpStreamInputHandle: RnpStreamInputHandleConstructor;
  RnpStreamOutputHandle: RnpStreamOutputHandleConstructor;
  RnpUidHandle: RnpUidHandleConstructor;
  RnpVerifyOpHandle: RnpVerifyOpHandleConstructor;
  RnpVerifySigHandle: RnpVerifySigHandleConstructor;
}

export interface RnpEncryptOpHandle {
  _destroy(): void;
  addRecipient(key: RnpKeyHandle): void;
  addPassword(pw: string, s2k_hash: string, iterations: number, s2k_cipher: string): void;
  setArmor(a: boolean): void;
  setCipher(c: string): void;
  setHash(h: string): void;
  setCompression(alg: string, level: number): void;
  setAead(alg: string): void;
  setCreationTime(t: number): void;
  setExpirationTime(t: number): void;
  setFileName(n: string): void;
  setFileMtime(t: number): void;
  execute(): void;
}

export interface RnpEncryptOpHandleConstructor {
}

export interface RnpFfiHandle {
  setPasswordProvider(callback: unknown): void;
  setKeyProvider(callback: unknown): void;
  setTimestamp(t: number): void;
  _id(): number;
  _destroy(): void;
}

export interface RnpFfiHandleConstructor {
  create(pub_format: string, sec_format: string): RnpFfiHandle;
}

export interface RnpGenerateOpHandle {
  _destroy(): void;
  setBits(bits: number): RnpGenerateOpHandle;
  setHash(hash: string): RnpGenerateOpHandle;
  setDsaQbits(q: number): RnpGenerateOpHandle;
  setCurve(c: string): RnpGenerateOpHandle;
  setProtectionPassword(pw: string): RnpGenerateOpHandle;
  setRequestPassword(r: boolean): RnpGenerateOpHandle;
  setProtectionCipher(c: string): RnpGenerateOpHandle;
  setProtectionHash(h: string): RnpGenerateOpHandle;
  setProtectionIterations(i: number): RnpGenerateOpHandle;
  setProtectionMode(m: string): RnpGenerateOpHandle;
  addUsage(u: string): RnpGenerateOpHandle;
  clearUsage(): RnpGenerateOpHandle;
  setUserid(u: string): RnpGenerateOpHandle;
  setExpiration(e: number): RnpGenerateOpHandle;
  setV6Key(): RnpGenerateOpHandle;
  execute(): void;
  getKey(): RnpKeyHandle;
}

export interface RnpGenerateOpHandleConstructor {
}

export interface RnpIdentifierIteratorHandle {
  _destroy(): void;
  next(): string;
}

export interface RnpIdentifierIteratorHandleConstructor {
}

export interface RnpInputHandle {
  _destroy(): void;
}

export interface RnpInputHandleConstructor {
  fromBytes(data_ptr: number, len: number): RnpInputHandle;
}

export interface RnpKeyHandle {
  _destroy(): void;
  fingerprint(): string;
  keyid(): string;
  grip(): string;
  primaryGrip(): string;
  primaryFingerprint(): string;
  version(): number;
  alg(): string;
  bits(): number;
  dsaQbits(): number;
  curve(): string;
  creation(): number;
  expiration(): number;
  setExpiration(expiry: number): void;
  isValid(): boolean;
  validTill64(): number;
  isRevoked(): boolean;
  revocationReason(): string;
  isExpired(): boolean;
  isLocked(): boolean;
  lock(): void;
  unlock(password: string): void;
  isProtected(): boolean;
  protect(password: string, cipher: string, hash: string, iterations: number): void;
  unprotect(password: string): void;
  protectionType(): string;
  protectionCipher(): string;
  protectionHash(): string;
  protectionIterations(): number;
  isPrimary(): boolean;
  isSub(): boolean;
  haveSecret(): boolean;
  havePublic(): boolean;
  subkeyCount(): number;
  subkeyAt(idx: number): RnpKeyHandle;
  primaryUid(): string;
  uidCount(): number;
  uidAt(idx: number): string;
  packetsToJson(flags: number): string;
  export(_out: RnpOutputHandle, flags: number): void;
  exportAutocrypt(_out: RnpOutputHandle, subkey: RnpKeyHandle | null, uid: string, flags: number): void;
  exportRevocation(_out: RnpOutputHandle, flags: number, hash: string, reason_code: string, reason_text: string): void;
  revoke(flags: number, hash: string, reason_code: string, reason_text: string): void;
  remove(flags: number): void;
  addUid(uid: string, hash: string, expiration: number, key_flags: number, primary: boolean): void;
}

export interface RnpKeyHandleConstructor {
}

export interface RnpOutputHandle {
  bytes(): unknown;
  _destroy(): void;
}

export interface RnpOutputHandleConstructor {
  toBytes(): RnpOutputHandle;
}

export interface RnpSignOpHandle {
  _destroy(): void;
  addSignature(signer: RnpKeyHandle, hash: string, creation: number, expiration: number): void;
  setArmor(a: boolean): void;
  setCompression(alg: string, level: number): void;
  setHash(h: string): void;
  setCreationTime(t: number): void;
  setExpirationTime(t: number): void;
  setFileName(n: string): void;
  setFileMtime(t: number): void;
  execute(): void;
}

export interface RnpSignOpHandleConstructor {
}

export interface RnpSignatureHandle {
  _destroy(): void;
  type(): string;
  alg(): string;
  hashAlg(): string;
  creation(): number;
  expiration(): number;
  keyFlags(): number;
  primaryUid(): boolean;
  keyid(): string;
  keyFprint(): string;
  signer(): string;
  revoker(): string;
  revocationReason(): string;
  trustLevel(): number;
  subpacketCount(): number;
  errorCount(): number;
  errorAt(idx: number): string;
  isValid(flags: number): boolean;
  packetToJson(flags: number): string;
}

export interface RnpSignatureHandleConstructor {
}

export interface RnpStreamInputHandle extends RnpInputHandle {
  _destroy(): void;
}

export interface RnpStreamInputHandleConstructor {
  create(reader: unknown): RnpStreamInputHandle;
}

export interface RnpStreamOutputHandle extends RnpOutputHandle {
  finish(): void;
  _destroy(): void;
}

export interface RnpStreamOutputHandleConstructor {
  create(writer: unknown): RnpStreamOutputHandle;
}

export interface RnpUidHandle {
  _destroy(): void;
  type(): number;
  data(): string;
  isPrimary(): boolean;
  isValid(): boolean;
  isRevoked(): boolean;
  signatureCount(): number;
  signatureAt(idx: number): RnpSignatureHandle;
}

export interface RnpUidHandleConstructor {
}

export interface RnpVerifyOpHandle {
  _destroy(): void;
  signatureCount(): number;
  signatureAt(idx: number): RnpVerifySigHandle;
  execute(): void;
}

export interface RnpVerifyOpHandleConstructor {
}

export interface RnpVerifySigHandle {
  status(): number;
  hashAlg(): string;
  sigAlg(): string;
  signerKeyid(): string;
  creation(): number;
  expiration(): number;
  _destroy(): void;
}

export interface RnpVerifySigHandleConstructor {
}

// ---- Manual overrides -------------------------------------------
// The codegen above reflects C++ signatures verbatim. A handful of
// methods return emscripten::val that we KNOW will be a specific JS
// type at runtime (e.g. Uint8Array for OutputHandle.bytes()). Patch
// those here so consumers don't have to cast.

export interface RnpOutputHandle {
  bytes(): Uint8Array;
}
